### ISSUE TITLE
It cuts off other modules.

### ISSUE THREAD

**Issue by griggscarsos** [jbamford/MMM-PenPlotter#1]
How can I fix the pen plotter covering up my other modules?
![20230325_101528](https://user-images.githubusercontent.com/71665554/227784683-4bb7a3ba-0da4-44d7-a423-f562291f4f23.jpg)

**Comment by jbamford** [comment]
@griggscarsos can you please share your config file? It looks like you might have instantiated the module twice.

**Comment by RomainLG** [comment]
@jbamford I have the same issue, the render happens on a black background that blocks the other modules
![IMG_20230919_132215](https://github.com/jbamford/MMM-PenPlotter/assets/13045542/776c5afd-b1da-4ae9-acb7-f2bd4eb5fd23)
